### ISSUE TITLE
RFE: support org level self hosted runner

### ISSUE THREAD

**Issue by rootfs** [equinix-labs/metal-runner-action#10]
Per [this line](https://github.com/equinix-labs/metal-runner-action/blob/main/action.yml#L38), the metal runner only supports repo level runner. This doesn't work for organization level runner per doc [here](https://docs.github.com/en/rest/authentication/permissions-required-for-fine-grained-personal-access-tokens?apiVersion=2022-11-28#organization-permissions-for-self-hosted-runners)

It would be great if both repo and orgs level runner can be supported.

**Comment by ocobles** [comment]
fixed in #11
