### ISSUE TITLE
RFE: support custom user data

### ISSUE THREAD

**Issue by rootfs** [equinix-labs/metal-runner-action#13]
I want to create a metal instance with custom user data so that i can reserve cpu cores and disable CPU P state, so that i can use the reserved cores to run VMs.

I have tested the following user data and it works on the Equninix console. 

```bash
runcmd:
  - cp /boot/grub2/grub.cfg /boot/grub2/grub.cfg.bak
  - sed -i '/^[[:space:]]*linux / s/$/ isolcpus=1-7,9-15 intel_pstate=disable/' /boot/grub2/grub.cfg
  - reboot
```

Since the runner has already set the user data [here](https://github.com/equinix-labs/metal-runner-action/blob/main/action.yml#L64), it could be possible to check if there is a custom user data provided and run it after runner configuration is finished.

cc @vprashar2929

**Comment by displague** [comment]
[`custom_script`](https://github.com/equinix-labs/metal-runner-action?tab=readme-ov-file#inputs) option was included in [v0.4.0](https://github.com/equinix-labs/metal-runner-action/releases/tag/v0.4.0)
